version: '3'

services:

  consul-agent-1: &consul-agent
    image: consul:latest
    networks:
      - ded-net
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"
    container_name: consul-agent-1

  consul-agent-2:
    <<: *consul-agent
    container_name: consul-agent-2

  consul-agent-3:
    <<: *consul-agent
    container_name: consul-agent-3

  consul-server-1: &consul-server
    <<: *consul-agent
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"
    container_name: consul-server-1

  consul-server-2:
    <<: *consul-server
    container_name: consul-server-2

  consul-server-bootstrap:
    container_name: consul-server-bootstrap
    <<: *consul-agent
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"


# consul:
#   image: consul
#   container_name: consul-server
#   expose:
#     - "8500"
#   ports:
#     - "8500:8500"
#   networks:
#     - ded-net


  gateway-service:
    container_name: gateway
    build:
      context: generic-java-docker/
      dockerfile: Dockerfile
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./gateway-service/target/:/app/
    networks:
      - ded-net
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul-agent-1
      - SPRING_CLOUD_CONSUL_DISCOVERY_HOSTNAME=gateway
      - SPRING_CLOUD_CONSUL_DISCOVERY_INSTANCE_ID=gateway
      - SPRING_CLOUD_CONSUL_DISCOVERY_SERVICENAME=gateway-service

  caller-service1:
    container_name: caller1
    build:
      context: generic-java-docker/
      dockerfile: Dockerfile
    volumes:
      - ./caller-service/target/:/app/
    networks:
      - ded-net
    expose:
      - "8091"
    ports:
      - "8091:8091"
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul-agent-2
      - SPRING_CLOUD_CONSUL_DISCOVERY_HOSTNAME=caller1
      - SPRING_CLOUD_CONSUL_DISCOVERY_INSTANCE_ID=caller1
      - SPRING_CLOUD_CONSUL_DISCOVERY_SERVICENAME=caller-service
      - SERVER_PORT=8091

  caller-service2:
    container_name: caller2
    build:
      context: generic-java-docker/
      dockerfile: Dockerfile
    volumes:
      - ./caller-service/target/:/app/
    expose:
      - "8092"
    ports:
      - "8092:8092"
    networks:
      - ded-net
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul-agent-3
      - SPRING_CLOUD_CONSUL_DISCOVERY_HOSTNAME=caller2
      - SPRING_CLOUD_CONSUL_DISCOVERY_INSTANCE_ID=caller2
      - SPRING_CLOUD_CONSUL_DISCOVERY_SERVICENAME=caller-service
      - SERVER_PORT=8092

  callme-service1:
    container_name: callme1
    build:
      context: generic-java-docker/
      dockerfile: Dockerfile
    volumes:
      - ./callme-service/target/:/app/
    networks:
      - ded-net
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul-agent-1
      - SPRING_CLOUD_CONSUL_DISCOVERY_HOSTNAME=callme1
      - SPRING_CLOUD_CONSUL_DISCOVERY_INSTANCE_ID=callme1
      - SPRING_CLOUD_CONSUL_DISCOVERY_SERVICENAME=callme-service
      - SERVER_PORT=8093

  callme-service2:
    container_name: callme2
    build:
      context: generic-java-docker/
      dockerfile: Dockerfile
    volumes:
      - ./callme-service/target/:/app/
    networks:
      - ded-net
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul-agent-2
      - SPRING_CLOUD_CONSUL_DISCOVERY_HOSTNAME=callme2
      - SPRING_CLOUD_CONSUL_DISCOVERY_INSTANCE_ID=callme2
      - SPRING_CLOUD_CONSUL_DISCOVERY_SERVICENAME=callme-service
      - SERVER_PORT=8094

  consul-config-uploader:
    container_name: consul-config-uploader
    build:
      context: gateway-config/
      dockerfile: Dockerfile
    networks:
      - ded-net

networks:
  ded-net:
    external:
      name: dedicated-network