version: '2.1'

services:
  eureka1:
    container_name: eureka1
    build:
      context: generic-java-docker/
      dockerfile: Dockerfile
    expose:
      - "8761"
    ports:
      - "8761:8761"
    volumes:
      - ./service-registry/target/:/app/
    networks:
      - ded-net
    environment:
      - WAIT_TIME=0
      - SPRING_PROFILES_ACTIVE=eureka1
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka1:8761/eureka,http://eureka2:8762/eureka

  eureka2:
    container_name: eureka2
    build:
      context: generic-java-docker/
      dockerfile: Dockerfile
    expose:
      - "8762"
    ports:
      - "8762:8762"
    volumes:
      - ./service-registry/target/:/app/
    networks:
      - ded-net
    environment:
      - WAIT_TIME=10
      - SPRING_PROFILES_ACTIVE=eureka2
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka1:8761/eureka,http://eureka2:8762/eureka


  gateway-service:
    container_name: gateway
    build:
      context: generic-java-docker/
      dockerfile: Dockerfile
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./gateway-service/target/:/app/
    networks:
      - ded-net
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka1:8761/eureka,http://eureka2:8762/eureka
      - WAIT_TIME=20
      - EUREKA_INSTANCE_INSTANCEID=gateway
      - SERVER_PORT=8080

  caller-service1:
    container_name: caller1
    build:
      context: generic-java-docker/
      dockerfile: Dockerfile
    volumes:
      - ./caller-service/target/:/app/
    networks:
      - ded-net
    expose:
      - "8091"
    ports:
      - "8091:8091"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka1:8761/eureka,http://eureka2:8762/eureka
      - WAIT_TIME=20
      - EUREKA_INSTANCE_INSTANCEID=caller1
      - SERVER_PORT=8091

  caller-service2:
    container_name: caller2
    build:
      context: generic-java-docker/
      dockerfile: Dockerfile
    volumes:
      - ./caller-service/target/:/app/
    expose:
      - "8092"
    ports:
      - "8092:8092"
    networks:
      - ded-net
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka1:8761/eureka,http://eureka2:8762/eureka
      - WAIT_TIME=20
      - EUREKA_INSTANCE_INSTANCEID=caller2
      - SERVER_PORT=8092

  callme-service1:
    container_name: callme1
    build:
      context: generic-java-docker/
      dockerfile: Dockerfile
    volumes:
      - ./callme-service/target/:/app/
    networks:
      - ded-net
    environment:
      - SERVER_PORT=0
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka1:8761/eureka,http://eureka2:8762/eureka
      - WAIT_TIME=20
      - EUREKA_INSTANCE_INSTANCEID=callme1

  callme-service2:
    container_name: callme2
    build:
      context: generic-java-docker/
      dockerfile: Dockerfile
    volumes:
      - ./callme-service/target/:/app/
    networks:
      - ded-net
    environment:
      - SERVER_PORT=0
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka1:8761/eureka,http://eureka2:8762/eureka
      - WAIT_TIME=20
      - EUREKA_INSTANCE_INSTANCEID=callme2

networks:
  ded-net:
    external:
      name: dedicated-network