spring:
  application:
    name: gateway-service
  cloud:
    consul:
      host: consul-agent-1

    loadbalancer:
      service-discovery:
        timeout: PT5S
      cache:
        enabled: false
#        ttl: PT5S
      ribbon:
        enabled: false

    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: caller-service
          uri: lb://caller-service
          predicates:
            - Path=/caller/**
          filters:
            - RewritePath=/caller/(?<path>.*), /$\{path}
        - id: callme-service
          uri: lb://callme-service
          predicates:
            - Path=/callme/**
          filters:
            - RewritePath=/callme/(?<path>.*), /$\{path}

server.port: 8080