spring:
  application:
    name: gateway-service
  cloud:
    consul:
      host: consul-server-bootstrap
      config:
        format: YAML
      discovery:
        catalog-services-watch-delay: 100

    loadbalancer:
      service-discovery:
        timeout: PT5S
      cache:
        enabled: false
      ribbon:
        enabled: false

    gateway:
      discovery:
        locator:
          enabled: true

server.port: 8080